### ISSUE TITLE
Backend: Implementera kollisions-detektering

### ISSUE THREAD

**Issue by jemilolsson** [CAG-Contactor/Hunchback#2]
När vi har en karta ( #3 ), räkna ut när man kolliderar med något och låt detta påverka positionen på något lämpligt och/eller olämpligt sätt

**Comment by jemilolsson** [comment]
Håll i åtanke att "gubbens" position _inte_ är 1 pixel. 
Storleken på gubben är (för tillfället) 32x32 pixlar, och positionen som skickas till frontend bör ta hänsyn till detta. 
Positionen som backend skickar översätts till övre vänstra hörnet på gubben.

**Comment by joelbinn** [comment]
OBS! Kom ihåg att all "game state"-beräkning inkl. kollisionsdetektering skall utföras i backend.

**Comment by GabOzbek** [comment]
Kollision hanteringen är in checkad.
